mkdir build-conda
cd build-conda

cmake .. \
-D CMAKE_BUILD_TYPE:STRING="Release" \
-D GBS_USE_OCCT_UTILS:BOOL=FALSE \
-D GBS_USE_CUDA:BOOL=FALSE \
-D GBS_BUILD_TESTS:BOOL=FALSE \
-D GBS_USE_RENDER:BOOL=TRUE \
-D GBS_USE_PYTHON_BINDINGS=TRUE \
-D GBS_BUILD_DOC=FALSE \
-D GBS_USE_CUDA=FALSE \
-D CMAKE_INSTALL_PREFIX=$PREFIX \
-G "Ninja" \
-Wno-dev

ninja install

cd ..