python:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    # - 3.13
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]