package:
  name: gbs
  version:  0.0.0.2

source:  
  git_url: https://github.com/ssg-aero/gbs.git
  # path: ../

build:
requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake  
  host:
    - python
    - pybind11
    - occt >=7.4.0
    - nlopt
    - vtk >=9.0
    - eigen
    - boost >=1.74
    - gtest
    - sundials 
    - sphinx
    - sphinx-rtd-theme
    - breathe
    - doxgen
    - rapidjson
    - fmt
  run:
    - python
    - pytest
    - boost >=1.74
    - nlopt
    - vtk >=9.0
    - occt >=7.4.0
about:
  home: http://www.ssg-aero.com
  license: LGPL3
test:
  imports:
    - pygbs
