package:
  name: gbs
  version:  0.4.2
source:  
  # git_url: https://github.com/ssg-aero/gbs.git
  path: ../

build:
  number: 0
requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake >=3.28
    - python {{ python }}
  host:
    - python {{ python }}
    - python-devtools
    - pybind11
    - nlopt
    - vtk >=9.2
    - eigen >=3.3.9 # turns c+20 warning off
    - boost >=1.74
    - rapidjson
    - libiges
  run:
    - python {{ python }}
    - nlopt
    - vtk >=9.2
    - rapidjson
    - libiges
    - jupyterlab
    - pythreejs
    - pyvista
    - plotly
about:
  home: http://www.ssg-aero.com
  license: LGPL3
test:
  imports:
    - pygbs.gbs
