
context:
  version:  0.4.2

package:
  name: gbs
  version: ${{ version }}

source:  
  # git: https://github.com/ssg-aero/gbs.git
  # git_rev: 2ad7d87393fcbed8fb0b6bd943ee98478eb7a26c
  path: ../

extra:
  channels:
  - url: conda-forge
  - url: ssg-aero

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{"vs2022_win-64" if win}}
    - ninja
    - cmake >=3.28
    - python
  host:
    - python
    - python-devtools
    - pybind11
    - nlopt
    - vtk =9.3.0
    - eigen >=3.3.9 # turns c+20 warning off
    - boost
    - rapidjson
    - tbb
    - tbb-devel
    - libiges
  run:
    - python
    - nlopt
    - vtk >=9.2
    - rapidjson
    - libiges
    - jupyterlab
    - pythreejs
    - pyvista
    - plotly
about:
  homepage: http://www.ssg-aero.com
  # license: LGPL3
# test:
#   imports:
#     - pygbs.gbs
